# Generated by Django 3.2.16 on 2023-01-23 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiketModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiket', models.CharField(max_length=10)),
                ('jenis_aduan', models.CharField(max_length=100)),
                ('aduan', models.TextField()),
                ('kategori', models.CharField(choices=[('visa', 'Visa'), ('dokumen', 'dokumen'), ('nilai', 'nilai')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='upload/')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date_move', models.DateTimeField(auto_now=True)),
                ('state_move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiket.state')),
                ('tiket_move', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiket.tiketmodel')),
                ('user_move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=12)),
                ('nama', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='upload/foto/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
