# Generated by Django 3.2.16 on 2023-01-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movestate',
            name='tiket_move',
        ),
        migrations.AddField(
            model_name='tiketmodel',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiket.movestate'),
        ),
    ]
