# Generated by Django 3.2.16 on 2023-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0006_alter_movestate_tiket_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiketmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
