# Generated by Django 3.2.16 on 2023-01-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0007_alter_tiketmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiketmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('process', 'process'), ('finish', 'finish'), ('closed', 'closed')], default='pending', max_length=10, null=True),
        ),
    ]
