# Generated by Django 3.2.16 on 2023-01-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0008_tiketmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiketmodel',
            options={'permissions': (('manage_tiket', 'Can Manage Tiket'),)},
        ),
    ]
