# Generated by Django 3.2.16 on 2023-01-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0010_alter_tiketmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='upload/foto/'),
        ),
    ]
