# Generated by Django 3.2.16 on 2023-01-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0011_alter_mahasiswa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(choices=[('Informatika', 'Informatika'), ('Ilmu Komunikasi', 'Ilmu Komunikasi'), ('Tekanik', 'Tekanik'), ('Psikologi', 'Psikologi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
