# Generated by Django 3.2.16 on 2023-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0017_alter_movestate_user_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='movestate',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
