# Generated by Django 3.2.16 on 2023-01-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0018_movestate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movestate',
            name='slug',
        ),
    ]
