# Generated by Django 3.2.16 on 2023-01-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0019_remove_movestate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiketmodel',
            name='status',
        ),
    ]
