# Generated by Django 3.2.16 on 2023-01-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0020_remove_tiketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movestate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movestate',
            name='date_move',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
