# Generated by Django 3.2.16 on 2023-01-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0021_auto_20230128_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiketmodel',
            old_name='jenis_aduan',
            new_name='judul',
        ),
    ]
